In [13]:
'''
(1) How-to-count-distance-to-the-previous-zero For each value, count the difference of the distance from the previous
zero (or the start of the Series, whichever is closer) and if there are no previous zeros,print the position

Consider a DataFrame df where there is an integer column {'X':[7, 2, 0, 3, 4, 2, 5, 0, 3, 4]}

The values should therefore be [1, 2, 0, 1, 2, 3, 4, 0, 1, 2]. Make this a new column 'Y'.
import pandas as pd
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

(2) Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers.

(3) Find the sum of the values in s for every Wednesday

(4) Average For each calendar month

(5) For each group of four consecutive calendar months in s, find the date on which the highest value occurred.'''

# (1) How-to-count-distance-to-the-previous-zero
print("(1) part is \n")
import pandas as pd
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
b_temp=[]
z_pos = -1
for i, n in enumerate(df.X):
    if n == 0:
        z_pos = i
    b_temp.append(i - z_pos)
df['Y']=b_temp
print(df)
print("-"*80)

# (2) Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers.
print("(2) part is \n")
import pandas as pd
from numpy.random import randn
s= pd.Series(randn(len(pd.bdate_range('2015-01-01', '2015-12-31'))), index=pd.bdate_range('2015-01-01', '2015-12-31'))
print("pandas series\n",s)
print("-"*80)

# (3) Find the sum of the values in s for every Wednesday
print("(3) part is \n")
s_weekdays = s.groupby([lambda x: x.weekday]).sum()
print("sum of values for weekdays\n",s_weekdays) 
s_wednesday=s_weekdays[2] #0-Mon,1-Tue,2-Wed,3-Thu,4-Fri,5-Sat,6-Sun
print("sum of values for day-wednesday",s_wednesday) 
print("-"*80)

# (4) Average For each calendar month
print("(4) part is \n")
s_months = s.groupby([lambda x: x.month]).mean()
print("average of values for months\n",s_months)
print("-"*80)

# (5) For each group of four consecutive calendar months in s, find the date on which the highest value occurred.
print("(5) part is \n")
s_max = s.groupby([lambda x: x.month]).max()
print("maximum of values for months\n",s_max)
print("-"*80)
print("\nEnd of assignemnt")

(1) part is

   X  Y
0  7  1
1  2  2
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2
--------------------------------------------------------------------------------
(2) part is

pandas series
 2015-01-01   -0.367932
2015-01-02    0.063117
2015-01-05   -0.061016
2015-01-06    0.074077
2015-01-07   -0.468634
2015-01-08   -3.564611
2015-01-09   -1.907830
2015-01-12   -0.911433
2015-01-13   -0.031677
2015-01-14    0.899787
2015-01-15   -0.352667
2015-01-16   -0.658842
2015-01-19   -0.967617
2015-01-20    0.681652
2015-01-21   -1.293825
2015-01-22    0.857618
2015-01-23    0.988535
2015-01-26   -1.315548
2015-01-27   -1.154693
2015-01-28    0.415117
2015-01-29    1.972213
2015-01-30    1.557345
2015-02-02    0.387167
2015-02-03   -0.339767
2015-02-04    0.614105
2015-02-05    1.051651
2015-02-06   -0.230991
2015-02-09    0.308891
2015-02-10   -0.551618
2015-02-11   -0.997939
                ...
2015-11-20   -1.416058
2015-11-23   -1.281905
2015-11-24    0.274169
2015-11-25   -1.826402
2015-11-26    0.208962
2015-11-27    0.397605
2015-11-30   -0.704478
2015-12-01   -1.497082
2015-12-02    0.559612
2015-12-03    0.530001
2015-12-04    0.464556
2015-12-07   -0.875863
2015-12-08    0.275215
2015-12-09   -0.444249
2015-12-10   -1.683659
2015-12-11   -0.388557
2015-12-14    0.062869
2015-12-15    0.133285
2015-12-16    0.394003
2015-12-17    0.021850
2015-12-18    1.965952
2015-12-21    1.491951
2015-12-22    0.357481
2015-12-23   -0.530001
2015-12-24    0.534203
2015-12-25    0.095007
2015-12-28    0.545685
2015-12-29   -0.653327
2015-12-30   -0.119808
2015-12-31   -1.570307
Freq: B, Length: 261, dtype: float64
--------------------------------------------------------------------------------
(3) part is

sum of values for weekdays
 0   -1.871195
1   -8.557406
2    5.701163
3    7.553681
4   -1.978981
dtype: float64
sum of values for day-wednesday 5.701162942169105
--------------------------------------------------------------------------------
(4) part is

average of values for months
 1    -0.252130
2    -0.180953
3    -0.286344
4    -0.041391
5     0.121928
6     0.177587
7     0.232746
8    -0.020461
9     0.097986
10    0.234853
11   -0.055181
12   -0.014399
dtype: float64
--------------------------------------------------------------------------------
(5) part is

maximum of values for months
 1     1.972213
2     1.323678
3     1.475890
4     1.682798
5     2.147197
6     2.418598
7     1.506506
8     1.471043
9     2.409008
10    1.931881
11    2.530575
12    1.965952
dtype: float64
--------------------------------------------------------------------------------

End of assignemnt